### ISSUE TITLE
Loading Parser Problem

### ISSUE THREAD

**Issue by AhmedEwis** [adymaharana/VLCStoryGan#2]
Hello.

Thanks for sharing this superb and promising work!

I am facing some problems when loading the parser.
I have tried to keep the parse.py as it is but I got the following: 

Loading parser
usage: [-h] [--sum] N [N ...]
: error: the following arguments are required: N
An exception has occurred, use %tb to see the full traceback.
SystemExit: 2

But when I changed the parser.add_argument from positional arguments to the different argument I got the following:
"args has no attribute dataset".

Knowing that my args type is as outlined below:
**Namespace**(**{'data_dir <path_to_data_directory>': None, 'dataset pororo': 'pororo'})
which seems unworkable.

**Comment by adymaharana** [comment]
Hi Ahmed,

Thank you for your interest in our work! I appreciate that you find it promising. Let me try and see what's going on with the parser. I see that you have opened another thread about the parser itself. So, I am going to close this issue and continue on the other issue. 

Cheers.
