### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied error.

### ISSUE THREAD

**Issue by Hyeonjin1989** [adymaharana/VLCStoryGan#5]
Hi, 

When I run the train as specified in the [Readme](https://github.com/adymaharana/VLCStoryGan#training-vlc-storygan) , I encounter the issue seen in the screenshot below: **mat1 and mat2 shapes cannot be multiplied.** And when I tried debugging, I saw issues in [algo.train()](https://github.com/adymaharana/VLCStoryGan/blob/fe522602a5659972f53822a0349a8a0f2357d05e/train_vlcgan.py#L205)  -> [netG.sample_videos](https://github.com/adymaharana/VLCStoryGan/blob/fe522602a5659972f53822a0349a8a0f2357d05e/vlcgan/trainer_vlc.py#L311)  -> [self.ca_net](https://github.com/adymaharana/VLCStoryGan/blob/fe522602a5659972f53822a0349a8a0f2357d05e/vlcgan/model.py#L891). And the reason of this error is that the `content_input` shape is [12x1780] , while the [fc](https://github.com/adymaharana/VLCStoryGan/blob/fe522602a5659972f53822a0349a8a0f2357d05e/vlcgan/model.py#L99) in `self.ca_net` in/output size is [640x248].

![image](https://user-images.githubusercontent.com/39545805/149017423-3625e1a9-bfc9-4158-89d4-ffca83be0350.png)

I'm unsure whether the dimension is incorrect, but I modified the fc layer dimension to run the code to the end. Unfortunately, the same errors have occurred several times after that, and since there is a case that the same Class is used in another function, I can't modify the layer anymore. 

How can I solve it? 
Or do I have a problem prior to training, such as 'prepare repository, extract constituency parses or dense captions', despite the fact that no issue has been shown to me?

**Comment by Hyeonjin1989** [comment]
It solved when I modify miscc/config.py value!

**Comment by AhmedEwis** [comment]
Hello @hyeonjinXZ ,
I am facing a similar issue in the training process after fixing many bugs, it is not working yet.
Did it work for you? (complete training and evaluation)
If yes can you share the updated files through my email: eng_ahmed95@outlook.com

**Comment by hyeonjinXZ** [comment]
Hi @AhmedEwis .
I changed the conditions below in vlcgan/miscc/config.py:

1. __C.TEXT.DIMENSION = 128 --> __C.TEXT.DIMENSION = 356
2. __C.MART.pretrained_embeddings = '/ssd-playpen/home/adyasha/projects/data/glove.840B.300d.txt' --> __C.MART.pretrained_embeddings = './data/glove.840B.300d.txt' 
3. yaml_cfg = edict(yaml.load(f)) -->yaml_cfg = edict(yaml.safe_load(f))

If you have any other issues, please let me know. Thanks :)

**Comment by AhmedEwis** [comment]
Thanks @hyeonjinXZ 
I didn't go through the config.py file.
I am facing problem in the data loader in the middle of the training it stops.
![image](https://user-images.githubusercontent.com/65680238/154801932-517825b5-d3c7-48ce-b6f9-3280a43864b8.jpeg)
